NetherlandsForensicInstitute/confidence

confidence.py
tests/test_io.py

`loadf(~/project.yaml)` would attempt to open that exact file. Can't think of a use case where the result of expanding ~-like things to user paths is not the caller's intention.
By having the envvar config *file* loader just call `loadf`, `PROJECT_CONFIG_FILE=~/project.yaml` will also expand the user and read `/home/mommy/project.yaml`.

Expand home dirs for loadf and envvar file

---

README.rst
confidence.py
tests/test_io.py

Typically defaulting to `~/.config/`, the [XDG spec](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html) has a default place to put user configuration. There's also `${XDG_CONFIG_DIRS}`, that's been added as well in the meantime.

Load form XDG-specified directories

---

confidence.py
tests/test_io.py
tox.ini

- new keyword argument `default` for `loadf`, defaulting to `_NoDefault`;
- take old code path if `default=_NoDefault` *or* file argument exists;
- `return default` otherwise;
- change calls to `loadf` following `path.exists` calls to use `loadf` with `default=NotConfigured`;

Enable ignoring missing files for loadf (defaults unchanged)

---

confidence.py
tests/files/comments.yaml
tests/test_io.py

Fix for #23, default to empty dict for falsy return values of `yaml.load`. Fix located in `loadf`, `load_name` now calling `loadf` to simplify implementation.

Fix yaml.load returning None for documents without content

---

CHANGES.rst
confidence.py
tests/test_io.py

Underscores in environment variables are interpreted as separators for the resulting attributes on the configuration object. This made it impossible to specify a configuration key resulting in a namespace that contains an underscore. This PR enables underscores in configuration namespaces through environment variables by differentiating between single and dual underscores. Environment variable `NAME_NAME__SPACE_KEY=foo` would show up on a `Configuration` instance as `config.name_space.key` when 'name' is loaded by `confidence.load_name`.
References #19.

Enable escaping underscores in environment variables

---

CHANGES.rst
confidence.py
tests/test_namespace.py

Setting attributes has unforeseen side effects, particularly on `NotConfigured`. 
> Errors should never pass silently.
> — Tim Peters
References #26

Deny setting non-protected attributes

---

confidence.py
tests/test_namespace.py

Goes toward #28, using `warnings.warn` to alert users that particular configuration keys won't be accessible as attributes (`.get` will continue to work).

Warn about attribute collisions during merge and split of sources

---

CHANGES.rst
README.rst
confidence.py
tests/test_io.py
tests/test_loaders.py

As in #32, introduces `Locality` enum grouping loader templates and callables and `loaders` to create a custom load order.

Enable easy override of default load order

---

CHANGES.rst
confidence.py
tests/test_namespace.py

Adds a `missing` parameter to all load functions and the `Configuration` constructor, accepting either a `Missing` sentinel value (defaulting to the current behaviour) or a default value to be returned when an unconfigured key is requested through attribute access.
References #36.

Enable raising error for unconfigured keys

---

confidence/utils.py
tests/files/complicated.yaml
tests/test_dict.py
tests/test_references.py
tests/test_utils.py

Implementation by @bartbroere allows non-`str` keys, alternative 'fix' is to always coerce keys to `str`. One of the added tests is known to fail, we could view `_merge` as internal API and keep this function oblivious of the problem, knowing that all the `load*`-functions and the `Configuration` constructor will always call `_split_keys` which always calls the fix.
References #41, #43.

Dealing with non-str keys

---

CHANGES.rst
confidence/models.py
tests/test_references.py

Would
- crash during call to `_merge` if the reference is to be found outside the same source;
- cause value to be resolved during load, obscuring any value override from a potential 'later' source.
*Not* resolving keys during merge should resolve both bugs, leaving resolving of references to 'user-time'.

Fix bug when Configuration source is a Configuration instance containing a reference

---

CHANGES.rst
confidence/models.py
tests/test_pickling.py

As per #47, `pickle` is unable to encode a `Configuration` object, making its use complicated with some 3rd party libs. `_missing` is the culprit for this, so treating that in a special way using `__getstate__` and `__setstate__` resolves the issue.

Make Configuration instances picklable

---

CHANGES.rst
confidence/models.py
tests/test_references.py

Recursive references within the same value (e.g. `${reference.${within}.value}`) were broken due to the regular expression that matches a reference. While regular expressions aren't typically very good at recursive structures, this one seems workable with a small fix, making sure to only match the value not containing any of the reference syntax symbols. 
This might break somewhere unexpectedly in the future, but seems to not currently break any existing things :)

Restrict recursive reference pattern

---

CHANGES.md
confidence/models.py
tests/files/complicated.yaml
tests/test_namespace.py
tests/test_sequence.py

Wraps sequences in `Configuration` with a 'thin' wrapper that calls back to a `Configuration` instance for mapping values and calls 'itself' for sequence values. 
References #51.

Wrap sequences to enable list-of-dicts style configurations

---

CHANGES.md
confidence/models.py
confidence/utils.py
tests/test_defaults.py
tests/test_namespace.py

Rarely useful or used, the default was basically the only thing that made sense anyways.
Fixes #68.

Remove separator argument

---

confidence/io.py

References #83, confidence was hard to shut out of the logging as it used the root logger (oops!).

Use named logger in confidence.io

---

.github/workflows/test.yml
CHANGES.md
check-requirements.txt
confidence/__init__.py
confidence/utils.py
docs/use.rst
noxfile.py
test-requirements.txt
tests/test_namespace.py

As applied by many libs and recommended by some [source](https://realpython.com/python-logging-source-code/#library-vs-application-logging-what-is-nullhandler)s, default all of the `confidence.*` logging handlers to be silent; logging should be an opt-in.
Small local test makes the logging show up when using `logging.basicConfig(level=logging.DEBUG)`, so not sure exactly how silent this makes the lib (doing this before importing the io module didn't change that).

Silence logging by default

---

CHANGES.md
confidence/models.py
noxfile.py
tests/files/complicated.yaml
tests/test_sequence.py

Would simply return strings with references in them, surprisingly. See tests and `complicated.yaml` for intended change.

Resolve references in sequences

---

CHANGES.md
confidence/io.py
tests/test_io.py

Should aid in containerized setups, where volume-mounting a directory is a widely used implementation of shipping configuration to a container image. This also mimics paths used by many packages (e.g. elasticsearch, cassandra, ...).
This will however now aid in a setup where both `/etc/my-app/database.yaml` and `/etc/my-app/my-app.yaml` are volume mounted into a container, the former being ignored by confidence unless the application adds something `/etc/my-app/{name}.yaml` to the load order (come to think of it, adding that would cause `/etc/my-app/my-app.yaml` to be loaded twice :see_no_evil:).
Reviewers, please also checkout #94, we might be able to come up with a way to steal / reuse more well-known behaviours (like adding `/etc/{name}/{name}.{extension}.d/*`) in ways that would aid …

Add system-wide named directory + named file paths to default load order

---

CHANGES.md
check-requirements.txt
confidence/io.py
test-requirements.txt
tests/test_io.py

As per #98, the following would previously fail:
```python
for key, subtree config.items():
print(key, confidence.dumps(subtree))
```
for every subtree that turned out to be a simple value and not a subtree. Dumpers now use `_unwrap` to make sure any value will result in a YAML-encoded string. Additionally, when dumping to string, any trailing explicit document (`...`) end is removed. Use case that encountered this was hindered by it, YAML inserts it to support these values in streams, something not targeted by confidence (note that they still might be included in files, at YAML's discretion).

Enable dumping any object / chunk of configuration

---

CHANGES.md
confidence/__init__.py
confidence/io.py
confidence/models.py

Fixes #101.
#97 is still open, that might make more sense now `unwrap` is being made part of the public API. The readability thing is still up for debate though, and maybe not part of this PR.

Expose unwrap function as public API

---

CHANGES.md
confidence/models.py
tests/test_namespace.py
tests/test_sequence.py

Reprs for sequence types were overly verbose (sequence of `Configuration` objects would repeat the module name many times), potential recursive lists would cause breakages.

Improve sequence repr

---

README.md

Fixes a typo in the Readme preventing confusion amongst users of this library.

Update Readme to fix typo reflecting correct passage of kwargs

---

README.md

Use new 'logo' in README header

---

CHANGES.md
confidence/models.py
tests/test_dict.py
tests/test_pickling.py

Only raise the an error when `default=NoDefault`, as specified by `config['path.key']` and required by the internal reference resolver.
Closes #124

Mimic behaviour of dict get, avoid KeyError by default

---

CHANGES.md
README.md
confidence/__init__.py
confidence/formats.py
confidence/io.py
pyproject.toml
tests/test_formats.py
tests/test_io.py
tests/test_utils.py

Maybe most important: nothing changes for anyone just calling `confidence.loadf()` with a bunch of files or even `load_name()`.
*Reviewers: there's more diff here than I would have liked, note that the most important bits are in `confidence/formats.py` (the actual `Format` spec and parsing calls) and and `confidence/io.py` (changing of parameters and delegation of things to the provided format).*
---
Move all of the `yaml.safe_load` calls into a `YAML` format object, and put a `JSON` format object next to it for good measure. These `Format` type objects can be used to control 
- the file format being read (so currently JSON or YAML);
- the file suffix used in file name / path templates (previously extension, though the suffix includes the dot [as it does with …

Separate config file format(s) from I/O
